model:
  params:
    vocab_size: 21128
    embedding_dim: 300
    hidden_dim: 256
    num_layers: 2
    num_classes: 6
    use_extra_mlp: False
    mlp_ratio: [4, 2]
    mlp_dropout: [0.5, 0.2]
    recurrent_dropout: 0.2
    embedding_dropout: 0
    lr: 0.0003
    weight_decay: 0.05
    label_smoothing: 0.15

data:
  params:
    path: /mnt/d/codes/Swc_Data/ecg_data/ecg_train_data.json
    val_ratio: 0.1
    batch_size: 128
    num_workers: 3
    used_dataset: "ECG"

logger:
  params:
    save_dir: logs/
    name: ed

lightning:
  trainer:
    max_epochs: 300
    accelerator: "gpu"
    devices: 1
    enable_progress_bar: true # 显示进度条
