model:
  params:
    vocab_size: 21128
    embedding_dim: 300
    hidden_dim: 128
    num_layers: 2
    num_classes: 6
    use_extra_mlp: False
    mlp_ratio: [2, 1]
    mlp_dropout: [0.5, 0.2]
    recurrent_dropout: 0
    embedding_dropout: 0.95
    lr: 0.0001
    weight_decay: 0.7

data:
  params:
    path: ["/mnt/d/codes/Swc_Data/smp2020/train/usual_train.txt", "/mnt/d/codes/Swc_Data/smp2020/test/real_test/usual_test_labeled.txt"]
    val_ratio: 0
    batch_size: 256
    num_workers: 19
    used_dataset: "SMP2020"

logger:
  params:
    save_dir: logs/
    name: ed

lightning:
  trainer:
    max_epochs: 300
    accelerator: "gpu"
    devices: 1
    enable_progress_bar: true # 显示进度条
